### ISSUE TITLE
Issue detected with cookies

### ISSUE THREAD

**Issue by kevinhowbrook** [sivaramsi/manageyum#1]
![image](https://cloud.githubusercontent.com/assets/2128707/26399519/1ffe4c06-4075-11e7-9171-6d11e6b76f6c.png)

To recreate, add a google spreadsheet as a 'custom app' by pasting in the URL. Make an edit and you should see the error

**Comment by sivaramsi** [comment]
Yeah, we could recreate it at our end. We will release a patch and PR's welcome.

**Comment by sivaramsi** [comment]
Have removed the code that causes this bug.  Will be released in upcoming release.

**Comment by sivaramsi** [comment]
The fix is on 2.0.1 pre-release.(currently available for Mac)
